server:  port: 1111
spring:  application:    name: PhotoAppApi-eureka-server
eureka:  client:    register-with-eureka: false    fetch-registry: false    service-url:      deafaultZone:  http://localhost:1111/eureka