server:
  port: 4444

spring:
  application:
    name: zuul-router

eureka:
  client:
    service-url:
      defaultZone: http://localhost:1111/eureka/
    fetch-registry: true
    
zuul:
  prefix: /api
  routes:
    hi:
     path: /hi/**
     service-id: Hi-Service
     
    hello: 
     path: /hello/**
     service-id: Hello-Service
    

